# Project information
site_name: Studiums Notizen
site_description: 'Meine Notizen zu den Vorlesungen und Übungen an der HSR.'
site_author: 'Nikola Stankovic'
site_url: 'http://studium.stankovic.xyz/'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/nikolastankovic/studium'

# Copyright
copyright: 'Copyright (c) 2016 Nikola Stankovic'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  version: '1.0.0'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'nikolastankovic'
    
# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'